import Head from 'next/head'
import Header from './Header';

const Layout = ({ children }) => {
  return ( 
    <div>
      <Head>
        <title>Guitarla - Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />      
      {children}
    </div>    
  );
}
 
export default Layout;